-- criar tabela para guardar registros de vacinação - Brasil
CREATE TABLE vaccination (
    document_id varchar(50) NOT NULL,
    paciente_id varchar(100) NOT NULL,
    paciente_idade varchar(3),
    paciente_nascimento varchar(10),
	paciente_sexo varchar(1),
	paciente_racacor_codigo varchar(10),
	paciente_racacor_valor varchar(20),
	paciente_end_codibge varchar(10),
	paciente_end_codpais varchar(5),
	paciente_end_nomemunicipio varchar(50),
	paciente_end_nomePais varchar(50),
	paciente_end_uf varchar(2),
	paciente_end_cep varchar(10),
	paciente_nacionalidade varchar(30),
	estabel_cod varchar(10),
	estabel_razao_social varchar(100),
	estabel_nome_fantasia varchar(100),
	estabel_cod_municipio varchar(10),
	estabel_nome_municipio varchar(100),
	estabel_uf varchar(2),
	vacina_grupo_atend_cod varchar(10),
	vacina_grupo_atend_nome varchar(100),
	vacina_categoria_cod varchar(10),
	vacina_categoria_nome varchar(50),
	vacina_lote varchar(20),
	vacina_fabricante_nome varchar(100),
	vacina_fabricante_ref varchar(50),
	vacina_aplicacao varchar(10),
	vacina_dose varchar(50),
	vacina_codigo varchar(10),
	vacina_nome varchar(100),
	sistema_origem varchar(50),
	Primary Key (document_id)
);